/* Header for module box, generated by p2c */
#ifndef BOX_H
#define BOX_H

#include "pastrix.h"
#include "boxglobl.h"
#include "yapp.h"
#include "boxlocal.h"


void signalise_readlimit(short unr, bool today,
				char *name, short von, short bis);
void add_readday(short unr, int32_t count);
void begruessung(short unr);
void box_command_fract(short unr, char *command, bool return_);
void show_sortcheck(short unr);
void show_fullcheck(short unr);
bool erase_by_bid(bool reread, char *sbid, char *eraseabsender);
void set_forward(short unr, short unr_msg, char *quelle, char *option,
			short nr, short bis, char *to_box, char *from_box,
			char *lastvias);
void check_remote_erase(int32_t *seekp);
void add_remote_erase(char *absender, char *id1, char *rxfrom, char *id2);
void delete_brett_by_bid(char *brett, char *sfcall, char *bid,
				bool release, bool hidden);
bool select_file(short unr, char *pfad, char *name, char *titel);
bool analyse_boxcommand(short unr, char *eingabe, char *voll, bool return_);
short search_by_bid(char *brett, char *bid, bool hidden);
unsigned short read_brett(short unr, short outch, char *board,
  short von, short bis, short threshold, char *option, char *search, int32_t sfoffset,
  indexstruct *header);
unsigned short read_for_bcast(char *rubrik, short nr, char *vname, indexstruct *header);
void list_brett(short unr, char *board, short von, short bis, short threshold,
		       char *option, char *search);
void run_sysbatch(char *name);
void disp_logptr(short unr, int32_t checkct, bool bidsearch,
			boxlogstruct *logptr, char *hs);
bool check_access_ok(short unr, bool userfiles, bool nochb, bool wantchb,
			    bool wants_distcheck, bool wants_sendercheck, boxlogstruct *log);
void export_brett(short unr, char *brett, short s, short e, short threshold,
			 char *option1, char *search, char *fname);
bool set_reply_flag(short unr, char *brett, short nr);
void add_eraseby(char *call, indexstruct *header);

#endif /*BOX_H*/

/* End. */
