/* Header for module box_tim, generated by p2c */
#ifndef BOX_TIM_H
#define BOX_TIM_H

#include "pastrix.h"
#include "boxglobl.h"

typedef void (*dpuaproc)(const short unr, const char *s);

void do_quit(short unr, bool abort, bool verbose);
void end_boxconnect(short unr);
void spoolendcheck(short unr);
void tell_command(char *call, char *bid, char *frage);
void stop_tell(short unr);
bool tell_processing(char *tellfile);
void tell_check(void);
void timeout_check(short unr);
void show_mailbeacon(void);
void balise_check(void);
void add_zombie(pid_t pid, char *fname, short exitaction);
void kill_zombies(void);
void box_timing2(int64_t tct);
void start_mailbeacon_manually(short unr);
void start_crawl(short unr, char *par);
void query_crawl(short unr, char *query);
void get_dpboxusage(short *u1, short *u5, short *u15);
void print_dpboxusage(short unr, dpuaproc outputproc);
void block_mailbox(bool block, char *reason);

#endif /*BOX_TIM_H*/

