/* Header for module box_send, generated by p2c */
#ifndef BOX_SEND_H
#define BOX_SEND_H

#include "pastrix.h"
#include "boxglobl.h"

short box_s_chan(short unr);
void send_text3(short unr, bool first, char *eingabe,
		       bool return_);
void enter_lifetime(short unr, char *eingabe);
void box_txt2(bool first, short unr, char *betreff1);
void send_check(short unr, char *eingabe, bool is_user,
		       char msgtype);
void send_file0(short unr, bool in_send, char *fname);
bool send_file1(short unr, short *kanal, bool in_send,
			  short force_bin);
void send_sysmsg(char *tocall, char *tobbs, char *betreff, char *msg,
			short lt, char msgtype, short binmsg);

#endif /*BOX_SEND_H*/

