/* Header for module box_serv, generated by p2c */
#ifndef BOX_SERV_H
#define BOX_SERV_H

#include "pastrix.h"

extern bool in_servers(char *board);
extern bool do_server(char *sender, char *board, char *betreff,
		      char *tname, int32_t offset);
extern bool config_server(short unr, char *eingabe);
extern bool do_redist(char *absender, char *dest, char *betreff,
		      char *tname, int32_t offset);
extern bool do_ping(char *absender, char msgtype, char *subject, char *bid, char *tname,
		    int32_t offset, time_t rxtime);
#endif /*BOX_SERV_H*/

