/* Header for module box_mem, generated by p2c */
#ifndef BOX_MEM_H
#define BOX_MEM_H


#include "pastrix.h"
#include "boxglobl.h"
#include "yapp.h"
#include "boxlocal.h"

int32_t bidhash_active(void);
int32_t hboxhash_active(void);
void disp_bidhash(short unr);
void disp_hboxhash(short unr);
void clear_bidhash(void);
void clear_hboxhash(void);
void load_initial_hbox(void);
void add_bptr(char *call, int32_t bpos);
int32_t load_hbox(short hboxhandle, char *call, hboxtyp *hbox);
int32_t get_binstart(char *puffer, int32_t size, char *fname);
void add_line_to_buff(char **buf1, int32_t *size1, int32_t inspos,
			     char *srline);
void write_msgid(int32_t nr, char *ibuf);
bool check_double(char *new_id);
int32_t bull_mem(char *new_id, bool delet);
void multiple_bullcheck(short ct, bidchecktype bidcheck,
			       bidarrtype bidarr);
void pack_entry(char **puffer, int32_t *size, short *pmode);
int32_t true_bin(char *zeile);

#endif /*BOX_MEM_H*/

