/* Header for module box_sys, generated by p2c */
#ifndef BOX_SYS_H
#define BOX_SYS_H

#include "pastrix.h"
#include "boxglobl.h"

typedef void (*cbaproc)(const short unr, const char *s);

void box_rtitle(bool set_it, short unr, char *rtitle);
void box_ttouch(short unr);
void show_ext_command_result(short unr);
void update_dp2(short unr);
void update_dp(short unr, char *eingabe);
void write_file2(short unr, char *eingabe);
void write_file(short unr, char *eingabe);
void yapp_responses(short unr, char *info, int32_t infosize);
void yapp_input(short unr, char *info, int32_t infosize);
bool read_file(bool delete_afterwards, short unr, char *eingabe);
bool read_filepart(short unr);
void abort_fileread(short unr);
void read_file_immediately(bool delete_afterwards, short unr, char *eingabe);
void show_file_dir(short unr, char *eingabe);
void calc_boxactivity(short unr, cbaproc outputproc);
void show_boxactivity(short unr);
void check_sysanswer(short unr, char *eingabe);
void answer_sysrequest(short unr, bool MD2, bool MD5);
void show_stat(short unr, short x);
void update_digimap(short unr, char *updatefile);
void calc_lonstr(double lon, char *str);
void calc_latstr(double lat, char *str);
void show_prefix_information(short unr, char *call, char *loc);
void calc_qthdist(short unr, char *loc1, char *loc2);
void show_user(short unr, char *call, char *option);
void set_password(short unr, bool superv, char *eingabe);
void import_pw(short unr, char *eingabe);
void change_unprotomode(short unr, char *eingabe);
void change_md2sf(short unr, char *eingabe, bool MD5);
void change_fbbmode(short unr, char *eingabe);
void change_prompt(short unr, char *eingabe);
void change_mailbeacon(short unr, char *eingabe);
void change_readlock(short unr, char *eingabe);
void change_ttl(short unr, char *eingabe);
void change_startup(short unr, char *eingabe);
void change_mybbs(short unr, char *callx, char *bbs, time_t updatetime,
			 char *level, char mybbsmode, bool update, bool fwd);
void change_levels(short unr, short cnr, char *callx, short lvl);
void change_name(short unr, char *callx, char *w);
bool valid_language(char *lan);
void show_languages(short unr);
void change_language(short unr, char *callx, char *w);
void show_systemtime(short unr);
void new_login(short unr, char *times);
void show_version(short unr, bool extended);
void disc_user(short unr, char *eingabe);
void write_ctext(short unr, char *eingabe);
void enter_ctext(short unr);
void search_bull(short unr, char *w, bool kill, bool add);
void set_talk_mode(short unr, char *w);
void end_talk_mode(short unr, bool prompt);
void talk_line(short unr, char *eingabe);
void msgwuser(short unr, bool immediate, char *s, bool cr);
void send_msg(short unr, char *w, char *eingabe);
void reset_to_term(short unr, bool to_sat, bool to_node);
bool open_shell(short unr, bool transparent);
void call_runprg(bool extern_, short unr, char *fname,
			char *rkommando, bool full_gem, char *add_environment);
void set_comp_mode(short unr, char *w);
void stelle_uhr(char *eingabe, bool datum);
void calc_pwdb(char *call, char *code, char *pw);
void gimme_five_pw_numbers(char *pw, char *numbers);
void calc_pwtn(char *call, char *code, char *pw);
void jitter_pwtn(char *pw);
void generate_dbpwfile(short unr, char *fname, char *options);
bool is_german(char *w);
bool for_german_readers(char *call1, char *call2, char *mbx);
void sig_german_authinfo(char *call, char *mbx, char *ret);
void create_sfstat(short unr, char *eingabe);
void generate_sfstat(short unr);
void readjust_dayly_sfcount(void);
void do_config(short unr, char *filename, char *eingabe);
void do_stripcr(short unr, char *filename);
void set_maxread(short unr, char *w, char *eingabe);

#endif /*BOX_SYS_H*/

