/* Header for module boxbcast, generated by p2c */
#ifndef BOXBCAST_H
#define BOXBCAST_H

#include "pastrix.h"

typedef void (*cbbproc)(const short unr, const char *s);

void load_boxbcastparms(char *name);
void free_boxbcastdesc(void);
void boxbcasttxtimer(void);
void show_bcastactivity(short unr, cbbproc outputproc);
void bccallback(int32_t l);

#endif /*BOXBCAST_H*/

