/* Header for module boxfserv, generated by p2c */
#ifndef BOXFSERV_H
#define BOXFSERV_H

#include "pastrix.h"

void analyse_smode_command(short unr, char *eingabe, bool return_);
void sig_7plus_incoming(bool priv, char *name, char *original, char *board);
void smode_timer(void);

#endif /*BOXFSERV_H*/

