/* Header for module boxglobl, generated by p2c */
#ifndef BOXGLOBL_H
#define BOXGLOBL_H

#include "pastrix.h"

#ifdef BOXGLOBL_G
# define vextern
#else
# define vextern extern
#endif



typedef void (*boxproc1type)(char *s);
typedef void (*boxproc2type)(short i);
typedef void (*boxproc0type)(void);
typedef void (*boxproc3type)(short i, char *s);
typedef void (*boxproc5type)(short i, char *s, bool b);
typedef void (*boxproc6type)(short i, short t);
typedef void (*boxproc7type)(short i, bool b);
typedef void (*boxproc8type)
  (short i, char *s1, char *s2, bool b1, bool b2, bool b3);
typedef void (*boxproc9type)
  (bool b, char *s1, short i, short k, int32_t l1, int32_t l2, int32_t l3, char *s2);
typedef void (*boxproc10type)(int32_t l);
typedef void (*boxproc11type)(char *s, bool b);
typedef void (*boxproc12type)
  (char *s, char *p, int32_t l1, int32_t l2, bool b1, bool b2, bool b3);
typedef void (*boxproc13type)(short i, bool b, char *s);
typedef void (*boxproc14type)(char *s, char **p, int32_t *l, int32_t k);
typedef void (*boxproc15type)(char *s);
typedef void (*boxproc16type)(char *s);
typedef void (*boxproc17type)(short i1, short i2, short i3);
typedef void (*boxproc18type)
  (short i1, short i2, short i3, bool b, char *p, int32_t l);
typedef void (*boxproc19type)
  (short i1, short i2, short i3, const char *s, bool b);
typedef void (*boxproc20type)(short i, char *s);
typedef void (*boxproc20atype)(short i, char *s, short iface, char *qrg);
typedef void (*boxproc21type)(short i, char *s, bool b);
typedef void (*boxproc21atype)(short i, char *s, bool b, short iface);
typedef void (*boxproc22type)(short i, char *s);
typedef void (*boxproc23type)(short i, char *s);
typedef void (*boxproc24type)(bool b);

typedef unsigned short (*boxfunc3type)(short x);
typedef short (*boxfunc2type)(short x);
typedef short (*boxfunc1type)(void);
typedef bool (*boxfunc0type)(void);
typedef int32_t (*boxfunc4type)(void);
typedef int32_t (*boxfunc5type)(short i);
typedef bool (*boxfunc6type)(short i, char *s1, char *s2);
typedef unsigned short (*boxfunc7type)(void);
typedef bool (*boxfunc8type)(short x);
typedef short (*boxfunc9type)(char *s1, char *s2);
typedef bool (*boxfunc10type)(char *s1, char *s2, char *s3);
typedef bool (*boxfunc11type)(bool b);
typedef int32_t (*boxfunc12type)(short i1, short i2, short i3);
typedef void (*boxgetstatustype)(bool sysop, char **p, int32_t *sz);
typedef void (*boxfreestatptype)(char **p);

void boxpushmonstat(short tnc);
void boxpopmonstat(short tnc);
void boxpushunproto(short tnc);
void boxpopunproto(short tnc);
void boxsendallbufs(void);
void boxloadgreeting(void);
void boxsetamouse(void);
void boxsetbmouse(void);
void boxsetcompwait(short chan, short v);
void boxreadallbuffers(void);
void boxsaveallbuffers(void);
short boxmodemport(void);
int32_t boxaktqrg(void);
int32_t boxtncqrg(short i);
void boxsetbox(short i, short t);
void boxsetwasbox(short i, short t);
void boxsetnode(short i, bool b);
void boxstartconnect(short i, char *s1, char *s2, bool b1,
			    bool b2, bool b3);
short boxcallgemprg(char *s1, char *s2);
void boxsgdial1(void);
void boxegdial1(void);
void boxsgdial(void);
void boxegdial(void);
void boxwait(int32_t l);
void boxrgdial1(char *s);
void boxendbusy(void);
void boxprprefix(short i, bool b, char *s);
unsigned short boxruntime(void);
void boxfreemostram(bool b);
void boxstartedit(char *s, char *p, int32_t l1, int32_t l2, bool b1,
			 bool b2, bool b3);
void boxedit(char *s, char **p, int32_t *l, int32_t k);
void boxcancelmultibox(void);
void boxprreset(char *s);
void boxprkill(short i, char *s);
void boxprdir(short i, char *s);
bool boxinitmodem(bool b);
bool boxexitmodem(bool b);
void boxendmodem(void);
void boxspoolfend(short chan);

vextern boxfunc1type boxboxssid, boxnodessid;
vextern boxproc7type boxsetboxsf;
vextern boxproc23type boxprwprg2;
vextern boxgetstatustype boxgetstatus;
vextern boxfreestatptype boxfreestatp;
vextern boxproc16type boxprotokoll;
vextern boxproc2type boxendbox, boxpacketendbox;
vextern boxfunc2type boxunackframes;
vextern boxfunc1type boxtnccount;
vextern boxproc20atype boxsetunproto;
vextern boxproc21atype boxsendpline;
vextern boxfunc0type boxgbstop;
vextern boxfunc2type boxgettncmonchan;
vextern boxproc20type boxsetmonstat, boxsetunattmode;
vextern boxfunc3type boxgetpaclen;
vextern boxproc6type boxsetrwmode;
vextern boxproc7type boxsetboxbin, boxpabortsf;
vextern boxfunc6type boxpboxsf;
vextern boxproc2type boxprdisc;
vextern boxfunc8type boxgetcompmode;
vextern boxproc7type boxsetcompmode;
vextern boxproc9type boxsetgdial;
vextern boxfunc0type boxhoststarted;
vextern boxproc0type boxcheckdiskspace;
vextern boxproc11type boxalert2;
vextern boxproc1type boxbusy;
vextern boxfunc10type boxgetfilename;
vextern boxfunc12type boxspoolstatus;
vextern boxproc17type boxspoolabort;
vextern boxproc18type boxmemspool;
vextern boxproc0type boxspoolread;
vextern boxproc19type boxspool;
vextern boxproc22type boxsetinpfile;

#undef vextern

#endif /*BOXGLOBL_H*/

/* End. */
