/* Header for module huffman, generated by p2c */

#ifndef HUFFMAN_H
#define HUFFMAN_H

#include "pastrix.h"

/* Hufman-Datenkompression dynamisch */

short enchuf(int gzip, int preserve_original, char *inf, char *outf, int crlfconv);
short dechuf(int gzip, int preserve_original, char *inf, char *outf, int crlfconv);

short enchufmem(int gzip, void *membase, int32_t size, void **outbase,
		       int32_t *outsize, char *outf, int crlfconv);
short dechufmem(int gzip, void *membase, int32_t size, void **outbase,
		       int32_t *outsize, char *outf, int crlfconv);

#endif /*HUFFMAN_H*/

