/* Header for module pastrix, generated by p2c */

#ifndef PASTRIX_H
#define PASTRIX_H


/* following headers are taken from: (note: it is only a small subset
 * of the original file) */

/* Header file for code generated by "p2c", the Pascal-to-C translator */

/* "p2c"  Copyright (C) 1989, 1990, 1991 Free Software Foundation.
 * By Dave Gillespie, daveg@csvax.cs.caltech.edu.  Version 1.20.
 * This file may be copied, modified, etc. in any way.  It is not restricted
 * by the licence agreement accompanying p2c itself.
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <inttypes.h>
#if defined(__linux__)
#include <limits.h>
#else
#include <sys/limits.h>
#endif

#ifndef TIME_MAX
#define TIME_MAX ((((time_t)1 << (sizeof(time_t) * 8 - 2)) - 1) * 2 + 1)
#endif


/* end of needed p2c.h definitions */


#define TICKSPERSEC	200	/* the 200 Hz counter */

#include "filesys.h" /* includes localised file system access for dpbox */

#define tab             '\t'

#ifdef __macos__
#include <time.h>
#else
#include <sys/time.h>
#endif

#if defined(__linux__) || defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__)
#include <signal.h>
#define DP_SIGHUP SIGHUP
#define DP_SIGTSTP SIGTSTP
#define DP_SIGTTIN SIGTTIN
#define DP_SIGTTOU SIGTTOU
#define DP_SIGPIPE SIGPIPE
#define DP_SIGKILL SIGKILL
#define DP_SIGTERM SIGTERM
#define DP_SIGSEGV SIGSEGV
#include <sys/wait.h>
#define DP_WNOHANG WNOHANG
#endif

#ifdef __macos__
#include <signal.h>
#define DP_SIGHUP SIGABRT
#define DP_SIGTSTP 1
#define DP_SIGTTIN 2
#define DP_SIGTTOU 3
#define DP_SIGPIPE 4
#define DP_SIGKILL 5
#define DP_SIGTERM SIGTERM
#define DP_SIGSEGV SIGABRT
#define DP_WNOHANG 6
#endif

short dp_randomize(short low, short hiw);
int64_t statclock(void);
#ifdef __macos__
int fork();
int kill(pid_t pid, int signal);
void setsid();
int waitpid(pid_t pid, int *res, int flag);
#endif

char *strsub(char *ret, char *s, int pos, int len);
int strpos2(char *s, char *pat, int pos);
void strdelete(char *s, int pos, int len);
void strinsert(char *src, char *dst, int pos);
void del_allblanks(char *s);
void del_leadblanks(char *s);
void del_lastblanks(char *s);
void lspacing(char *txt, short l);
void rspacing(char *txt, short l);
char upcase_(char ch);
char lowcase(char ch);
void upper(char *s);
void lower(char *s);
void strcpyupper(char *outs, char *ins);
void strcpylower(char *outs, char *ins);
bool zahl(char *s);
bool azahl(char *s);
bool rzahl(char *s);
int32_t hatoi(char *s);
void int2hstr(int32_t i, char *s);
void int2hchar(short i, char *c1, char *c2);
void hstr2str(char *h, char *s);
void str2hstr(char *s, char *h);
void del_mulblanks(char *s);
short count_words(char *s);
void get_quoted(char *inp, char *outp);
void get_pquoted(char **inp, char *outp);
void get_word(char *inp, char *outp);
void get_pword(char **inp, char *outp);
char *del_comment(char *z, char c);
void get_lline(char *buf, int32_t *posi, int32_t ende, char *zeile, short maxlen);
#define get_line(a, b, c, d) get_lline(a, b, c, d, 255)
void next_line(char *buf, int32_t *posi, int32_t ende);
void prev_line(char *buf, int32_t *posi);
void put_line(char *buf, int32_t *posi, const char *zeile);
void umlaut1(char *txt);
void umlaut2(char *txt);
void ersetze(char *oldstr, char *newstr, char *txt);
void gkdeutsch(char *name);
void sfbread(bool aslongaspossible, char *name, char **puffer, int32_t *size);

#define cut(string, size) string[size] = '\0'
#define nstrcpy(a, b, n) if (strncpy(a, b, n) != NULL) a[n] = '\0'
#define nstrcat(a, b, n) if (strncat(a, b, n) != NULL) a[n] = '\0'
#define maxram() 0x7fffffff
#define memavail__() 8000000
#define maxavail__() 8000000
#define move_b(quelle, ziel, size) memmove(ziel, quelle, size)

#if defined(__linux__) || defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__)
int64_t get_cpuusage(void);
#else
#define get_cpuusage() statclock()
#endif

#endif

