/* Header for module pastrix, generated by p2c */

#ifndef PASTRIX_H
#define PASTRIX_H


/* following headers are taken from: (note: it is only a small subset
 * of the original file) */

/* Header file for code generated by "p2c", the Pascal-to-C translator */

/* "p2c"  Copyright (C) 1989, 1990, 1991 Free Software Foundation.
 * By Dave Gillespie, daveg@csvax.cs.caltech.edu.  Version 1.20.
 * This file may be copied, modified, etc. in any way.  It is not restricted
 * by the licence agreement accompanying p2c itself.
 */


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <inttypes.h>
#if defined(__linux__)
#include <limits.h>
#else
#include <sys/limits.h>
#endif


/* end of needed p2c.h definitions */


#define TICKSPERSEC	200	/* the 200 Hz counter */

#include "filesys.h" /* includes localised file system access for dpbox */

#define tab             '\t'

#ifdef __macos__
#include <time.h>
#else
#include <sys/time.h>
#endif

#if defined(__linux__) || defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__)
#include <signal.h>
#define DP_SIGHUP SIGHUP
#define DP_SIGTSTP SIGTSTP
#define DP_SIGTTIN SIGTTIN
#define DP_SIGTTOU SIGTTOU
#define DP_SIGPIPE SIGPIPE
#define DP_SIGKILL SIGKILL
#define DP_SIGTERM SIGTERM
#define DP_SIGSEGV SIGSEGV
#include <sys/wait.h>
#define DP_WNOHANG WNOHANG
#endif

#ifdef __macos__
#include <signal.h>
#define DP_SIGHUP SIGABRT
#define DP_SIGTSTP 1
#define DP_SIGTTIN 2
#define DP_SIGTTOU 3
#define DP_SIGPIPE 4
#define DP_SIGKILL 5
#define DP_SIGTERM SIGTERM
#define DP_SIGSEGV SIGABRT
#define DP_WNOHANG 6
#endif

extern short dp_randomize(short low, short hiw);
extern int32_t searchbyte(char what, char *start, int32_t size);
extern int32_t maxavail__(void);
extern void RESETA(void);
extern void RESTART(void);
extern void WATCHDOG(short mode, short timer);
extern void VBLTIMER(short mode);
extern int32_t GETVBLTIMER(void);
extern void NOCRITIC(bool on);
extern char RAM_INIT(unsigned short size);
extern void RAM_EXIT(void);
extern void klang(short nr);
extern int32_t statclock(void);
extern void mtpause(void);

#ifdef __macos__
extern int fork();
extern int kill(pid_t pid, int signal);
extern void setsid();
extern int waitpid(pid_t pid, int *res, int flag);
#endif

extern char *mymemmem(char *haystack, int32_t haystacksize,
      	      	      char *needle, int32_t needlesize);
extern char *strsub(char *ret, char *s, int pos, int len);
extern int strpos2(char *s, char *pat, int pos);
extern void strdelete(char *s, int pos, int len);
extern void strinsert(char *src, char *dst, int pos);
extern void del_allblanks(char *s);
extern void del_leadblanks(char *s);
extern void del_lastblanks(char *s);
extern void lspacing(char *txt, short l);
extern void rspacing(char *txt, short l);
extern char upcase_(char ch);
extern char lowcase(char ch);
extern void upper(char *s);
extern void lower(char *s);
extern void strcpyupper(char *outs, char *ins);
extern void strcpylower(char *outs, char *ins);
extern bool zahl(char *s);
extern bool azahl(char *s);
extern bool rzahl(char *s);
extern int32_t hatoi(char *s);
extern int32_t batoi(char *s);
extern void int2hstr(int32_t i, char *s);
extern void int2hchar(short i, char *c1, char *c2);
extern void hstr2str(char *h, char *s);
extern void str2hstr(char *s, char *h);
extern void del_mulblanks(char *s);
extern short count_words(char *s);
extern void get_quoted(char *inp, char *outp);
extern void get_pquoted(char **inp, char *outp);
extern void get_word(char *inp, char *outp);
extern void get_pword(char **inp, char *outp);
extern char *del_comment(char *z, char c);
extern void get_lline(char *buf, int32_t *posi, int32_t ende, char *zeile, short maxlen);
#define get_line(a, b, c, d) get_lline(a, b, c, d, 255)
extern void next_line(char *buf, int32_t *posi, int32_t ende);
extern void prev_line(char *buf, int32_t *posi);
extern void put_line(char *buf, int32_t *posi, const char *zeile);
extern void umlaut1(char *txt);
extern void umlaut2(char *txt);
extern void ersetze(char *oldstr, char *newstr, char *txt);
extern void gkdeutsch(char *name);
extern void sfbread(bool aslongaspossible, char *name, char **puffer, int32_t *size);

#define cut(string, size) string[size] = '\0'
#define nstrcpy(a, b, n) if (strncpy(a, b, n) != NULL) a[n] = '\0'
#define nstrcat(a, b, n) if (strncat(a, b, n) != NULL) a[n] = '\0'
#define maxram() 0x7fffffffL
#ifdef __macos__
extern int32_t memavail__(void);
#else
#define memavail__() 8000000L
#define maxavail__() 8000000L
#endif
#define move_b(quelle, ziel, size) memmove(ziel, quelle, size)

#if defined(__linux__) || defined(__NetBSD__) || defined(__DragonFly__) || defined(__OpenBSD__)
extern int32_t get_cpuusage(void);
extern int32_t get_memusage(void);
#else
#define get_cpuusage() statclock()
#define get_memusage() 0
#endif

#endif

