/* Header for module status, generated by p2c */
#ifndef STATUS_H
#define STATUS_H

#include "pastrix.h"

void free_statp(char **p);
time_t get_sysruntime(void);
void get_status(bool sysop, char **p, int32_t *sz);
void get_cpuinf(char *cpu, char *mips);
void get_sysload(char *s);
void get_lastsysload(char *s);
void get_sysversion(char *s);
void get_linpack(char *s);

#endif

