/* Header for module status, generated by p2c */
#ifndef STATUS_H
#define STATUS_H

#include "pastrix.h"

extern void free_statp(char **p);
extern int32_t get_sysruntime(void);
extern void get_status(bool sysop, char **p, int32_t *sz);
extern void get_cpuinf(char *cpu, char *mips);
extern void get_sysload(char *s);
extern void get_lastsysload(char *s);
extern void get_sysversion(char *s);
extern void get_linpack(char *s);

#endif

