/* Header for module tools, generated by p2c */
#ifndef TOOLS_H
#define TOOLS_H

#include "pastrix.h"
#include "boxlocal.h"


typedef void (*fdoutproctype)(const short x, const char *s);

char conv_umlaut_from_local(char code);
char conv_umlaut_to_local(char code);
void conv_string_from_local(char *s);
void conv_string_to_local(char *s);
bool conv_file_umlaut(bool to_local, char *fname);
bool positive_arg(char *s);
void dp_watchdog(short what, short value);
short packer(bool gzip, bool preserve_original, bool encode, char *s1, char *s2, bool crlfconv);
short mempacker(bool gzip, bool encode, char *mem, int32_t size,
			   char **rmem, int32_t *rsize, char *f2,
			   bool crlfconv);
short call_prg(char *prog, char *par, char *redir);
short exec_prg(char *prog, char *par, char *redir);
void calc_MD5_pw(char *MD5prompt, char *MD5pw, char *MD5result);
void calc_MD2_pw(char *MD2prompt, char *MD2pw, char *MD2result);
void calc_MD_prompt(bool only_numbers, char *MDprompt);
short calc_prozent(int32_t v1, int32_t v2);
void stripcr(char *fn);
bool insecure(char *s);
#define useq(s1, s2) (strcasecmp(s1, s2) == 0)
short uspos(char *s1, char *s2);
bool get_fileline(char *fn, short line, char *l);
bool get_keyline(char *fn, char *key, bool casesense, char *l);
bool replace_keyline(char *fn, char *key, bool casesense,
			       char *e);
void expand_tabs(char *hs, short tabsize);
bool give_cookie(short x, fdoutproctype outproc, char *fname);
void calc_ixsecs_to_string(time_t l, char *hs);
void quick_speed(void);
int64_t get_cpu_speed(short mode);
short filecp(char *filea, char *fileb, char *root, bool del_source,
		    short x, fdoutproctype outproc);
void file_delete(short x, char *cmd, fdoutproctype outproc);
void file_dir(bool supervisor, char *path, char *options, short x,
		     fdoutproctype outproc);
char calccs(char *s);
char strcpycs(char *s2, char *s1);
void Gettimestr(char *ts);
void GetDatestr(char *ds);
unsigned short Make_DTime(short Hour, short Min, short Sec);
unsigned short Make_DDate(short Day, short Mon, short Yr);
void Get_DDate(unsigned short ddate, short *Day, short *Mon, short *Yr);
void Get_DTime(unsigned short dtime, short *Hour, short *Min, short *Sec);
time_t calcfdate(unsigned short date, unsigned short time);
time_t calc_ixtime(short d, short m, short y, short h, short mi, short s);
void decode_ixtime(time_t ix, short *d, short *m, short *y, short *h,
			  short *min, short *s);
void free_languages(languagetyp **root);
void user_language(char **root, int32_t *size, char *fname, char *call,
			  char *lan);
void load_languages(languagetyp **root, char *pfad);
void get_language(short nr, languagetyp *root, char *which, char *s);
short week_day(short d, short m, short y);
void wochentag(char *lan, short d, short m, short y, char *s);
void datum2string(unsigned short datum, char *datestring);
void datum22string(short day, short mon, short year, char *datestring);
void datum22string4(short day, short mon, short year, char *datestring);
void ixdatum2string(time_t datum, char *datestring);
void ixdatum2string4(time_t datum, char *datestring);
void zeit2string(unsigned short zeit, char *timestring);
void zeit22string(short hour, short min, short sec, char *timestring);
void dosdt2string(unsigned short date, unsigned short time, char *timestring);
void ixzeit2string(time_t zeit, char *timestring);
void ix2string(time_t zeit, char *timestring);
void ix2string4(time_t zeit, char *timestring);
time_t dos2ixtime(unsigned short ddate, unsigned short dtime);
void ix2dostime(time_t ix, unsigned short *ddate, unsigned short *dtime);
time_t string2ixtime(char *ds, char *ts);
unsigned short str2datum(char *datestring);
unsigned short str2zeit(char *timestring);
void unhpath(char *ins, char *outs);
void del_tnc3port(char *callin, char *callout);
void del_callextender(char *callin, char *callout);
void get_callextender(char *callin, char *callout);
bool callsign(char *rubrik);
bool hcallsign(char *rubrik);
time_t utc_clock(void);
time_t daydiff(unsigned short date1, unsigned short time1,
		    unsigned short date2, unsigned short time2);
unsigned short file_crc(short methode, char *name,
			       unsigned short preload, int32_t start, int32_t size);
bool prefix(char *call, char *subst, char *name, double *lon, double *lat,
		      short *waz, short *itu, char *continent);
void loc_dist(double o1, double n1, double o2, double n2,
		     double *entfernung, double *richtung, double *gegenrichtung);
bool calc_qth(char *loc, double *l, double *b);
bool get_wwloc(char *inp, char *outp);
bool get_digimap_data(bool bbs, char *call_, char *sysop, char *mbsysop, char *qthloc,
			 char *qthname, char *mbsystem, char *digisystem, char *remarks,
			 char *updatetime);
short merge_digimap_data(char *base, char *updfile);
short FuzzyMatching(char *CheckStr, char* SearchStr, short SearchStrLen,
      	      	      	    short NGram1Len, short NGram2Len);
void PrepareFuzzySearch(char *SearchStr, char *NormalisedStr,
			      	short *SearchStrLen, short *NGram1Len, short *NGram2Len);
bool check_other_callsyntax(char *syntax);

#define sys_ixtime() time(NULL)
bool compare(char *w, char *cmd);
#define conv_file_to_local(fname) conv_file_umlaut(true, fname)
#define conv_file_from_local(fname) conv_file_umlaut(false, fname)

#endif /*TOOLS_H*/

