/* Header for module yapp, generated by p2c */
#ifndef YAPP_H
#define YAPP_H

#include "pastrix.h"

typedef void (*yappchouttype)(const short unr, const char b);
typedef void (*yapplineouttype)(const short unr, const char *s);
typedef void (*yappbuffouttype)(short unr, char *base, int32_t size);

typedef struct yapptype {
  short			state, filefd, yappc;
  int32_t		total, filelength;
  time_t		touch;
  bool			delete_, write_;
  int32_t		maxfill, seekpos;
  short			unr;
  yappchouttype		chout;
  yapplineouttype	lineout;
  yappbuffouttype	buffout;
  yapplineouttype	statout;

  int32_t		outlen, outbufptr, buflen;
  char			outbuffer[512];
  char			buffer[1024];
  unsigned short	fdate, ftime;
  char			fname[256];
  char			yappdir[256];
} yapptype;

extern bool yapp_upload(bool init, bool abort, yapptype *yapp,
			   char *buffp, int32_t blen);
extern bool yapp_download(bool init, bool abort, yapptype *yapp,
			     char *buffp, int32_t blen);


#endif /*YAPP_H*/

/* End. */

